name: Dustin Byers
description: Update PR Description with Jira ticket/url
author: dustinbyershax
# inputs:
  # milliseconds: # change this
  #   required: true
  #   description: 'input description here'
  #   default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
